// Idempotent schema DDL, embedded so the deployed app can self-provision its
// database (e.g. a fresh Turso instance) without a separate migration step.
// Mirrors prisma/migrations/*/migration.sql with IF NOT EXISTS guards.
export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT,
    "email" TEXT NOT NULL,
    "emailVerified" DATETIME,
    "image" TEXT,
    "password" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "Account" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" DATETIME NOT NULL,
    CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "Quiz" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "sourceSummary" TEXT,
    "questionCount" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "purpose" TEXT NOT NULL DEFAULT 'standard',
    "sourceQuizId" TEXT,
    "sourceDocumentId" TEXT,
    "generationStatus" TEXT NOT NULL DEFAULT 'legacy',
    "targetQuestionCount" INTEGER,
    "firstBatchReadyAt" DATETIME,
    "generationError" TEXT,
    "groundingText" TEXT,
    "verificationStatus" TEXT NOT NULL DEFAULT 'pending',
    "verifiedAt" DATETIME,
    "verifierModel" TEXT,
    "verificationSummary" TEXT,
    "generatorModel" TEXT,
    "generatorPromptHash" TEXT,
    "verifierPromptHash" TEXT,
    CONSTRAINT "Quiz_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Question" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quizId" TEXT NOT NULL,
    "stem" TEXT NOT NULL,
    "options" TEXT NOT NULL,
    "correctOption" TEXT NOT NULL,
    "explanation" TEXT NOT NULL,
    "difficulty" TEXT NOT NULL,
    "topic" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "reviewConceptKey" TEXT,
    "blueprintItemId" TEXT,
    "optionExplanations" TEXT,
    "evidenceStatus" TEXT NOT NULL DEFAULT 'missing',
    "verdict" TEXT,
    "verificationDetail" TEXT,
    CONSTRAINT "Question_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Attempt" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quizId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" DATETIME,
    "score" INTEGER,
    "totalQuestions" INTEGER NOT NULL,
    CONSTRAINT "Attempt_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Attempt_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "AnswerRecord" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "attemptId" TEXT NOT NULL,
    "questionId" TEXT NOT NULL,
    "selectedOption" TEXT NOT NULL,
    "isCorrect" BOOLEAN NOT NULL,
    "timeMs" INTEGER,
    CONSTRAINT "AnswerRecord_attemptId_fkey" FOREIGN KEY ("attemptId") REFERENCES "Attempt" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "AnswerRecord_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ConceptReview" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "sourceQuizId" TEXT NOT NULL,
    "conceptKey" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "stage" INTEGER NOT NULL DEFAULT 0,
    "consecutiveCorrect" INTEGER NOT NULL DEFAULT 0,
    "dueAt" DATETIME,
    "lastReviewedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ConceptReview_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConceptReview_sourceQuizId_fkey" FOREIGN KEY ("sourceQuizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "SourceDocument" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "fullText" TEXT NOT NULL,
    "contentHash" TEXT NOT NULL,
    "originUrl" TEXT,
    "extractionMetadata" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "SourceDocument_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "SourceChunk" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sourceDocumentId" TEXT NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "pageStart" INTEGER,
    "pageEnd" INTEGER,
    "section" TEXT,
    "text" TEXT NOT NULL,
    "normalizedText" TEXT NOT NULL,
    "tokenCount" INTEGER NOT NULL,
    CONSTRAINT "SourceChunk_sourceDocumentId_fkey" FOREIGN KEY ("sourceDocumentId") REFERENCES "SourceDocument" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "SourceReference" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sourceDocumentId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "domain" TEXT NOT NULL,
    "authority" TEXT NOT NULL,
    CONSTRAINT "SourceReference_sourceDocumentId_fkey" FOREIGN KEY ("sourceDocumentId") REFERENCES "SourceDocument" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ChunkReference" (
    "sourceChunkId" TEXT NOT NULL,
    "sourceReferenceId" TEXT NOT NULL,
    PRIMARY KEY ("sourceChunkId", "sourceReferenceId"),
    CONSTRAINT "ChunkReference_sourceChunkId_fkey" FOREIGN KEY ("sourceChunkId") REFERENCES "SourceChunk" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ChunkReference_sourceReferenceId_fkey" FOREIGN KEY ("sourceReferenceId") REFERENCES "SourceReference" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "QuizBlueprintItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quizId" TEXT NOT NULL,
    "slot" INTEGER NOT NULL,
    "conceptKey" TEXT NOT NULL,
    "topic" TEXT NOT NULL,
    "objective" TEXT NOT NULL,
    "difficulty" TEXT NOT NULL,
    "skillType" TEXT NOT NULL,
    "retrievalQuery" TEXT NOT NULL,
    "requiredFacts" TEXT NOT NULL,
    "seedChunkIds" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "failureCode" TEXT,
    "batchIndex" INTEGER NOT NULL,
    CONSTRAINT "QuizBlueprintItem_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "QuizGenerationBatch" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quizId" TEXT NOT NULL,
    "batchIndex" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "startedAt" DATETIME,
    "completedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "QuizGenerationBatch_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "QuestionEvidence" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "questionId" TEXT NOT NULL,
    "sourceChunkId" TEXT NOT NULL,
    "quote" TEXT NOT NULL,
    "displayOrder" INTEGER NOT NULL,
    CONSTRAINT "QuestionEvidence_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "QuestionEvidence_sourceChunkId_fkey" FOREIGN KEY ("sourceChunkId") REFERENCES "SourceChunk" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "GenerationTrace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quizId" TEXT,
    "stage" TEXT NOT NULL,
    "batchIndex" INTEGER,
    "provider" TEXT,
    "model" TEXT,
    "durationMs" INTEGER NOT NULL,
    "inputTokens" INTEGER,
    "outputTokens" INTEGER,
    "cacheTokens" INTEGER,
    "questionCount" INTEGER,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL,
    "errorCode" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "GenerationTrace_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "StudyPlan" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "examTitle" TEXT NOT NULL,
    "examDate" DATETIME NOT NULL,
    "targetScore" INTEGER NOT NULL,
    "dailyMinutes" INTEGER NOT NULL,
    "availableDays" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "activeKey" TEXT,
    "stateVersion" INTEGER NOT NULL DEFAULT 1,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "StudyPlan_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "StudyPlanSource" (
    "studyPlanId" TEXT NOT NULL,
    "sourceDocumentId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("studyPlanId", "sourceDocumentId"),
    CONSTRAINT "StudyPlanSource_studyPlanId_fkey" FOREIGN KEY ("studyPlanId") REFERENCES "StudyPlan" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StudyPlanSource_sourceDocumentId_fkey" FOREIGN KEY ("sourceDocumentId") REFERENCES "SourceDocument" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "PlanConcept" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "studyPlanId" TEXT NOT NULL,
    "sourceDocumentId" TEXT NOT NULL,
    "sourceQuizId" TEXT,
    "conceptKey" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "importance" REAL NOT NULL DEFAULT 0.5,
    "objectives" TEXT NOT NULL,
    "seedChunkIds" TEXT NOT NULL,
    "proficiency" REAL NOT NULL DEFAULT 0,
    "lastActivityAt" DATETIME,
    "lastLessonAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "PlanConcept_studyPlanId_fkey" FOREIGN KEY ("studyPlanId") REFERENCES "StudyPlan" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CoachThread" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "studyPlanId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "CoachThread_studyPlanId_fkey" FOREIGN KEY ("studyPlanId") REFERENCES "StudyPlan" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CoachMessage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "threadId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "citations" TEXT,
    "pendingPlanUpdate" TEXT,
    "proposedActionId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CoachMessage_threadId_fkey" FOREIGN KEY ("threadId") REFERENCES "CoachThread" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CoachAction" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "studyPlanId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'proposed',
    "title" TEXT NOT NULL,
    "rationale" TEXT NOT NULL,
    "estimatedMinutes" INTEGER NOT NULL,
    "conceptKeys" TEXT NOT NULL,
    "sourceDocumentIds" TEXT NOT NULL,
    "payload" TEXT,
    "planStateVersion" INTEGER NOT NULL,
    "generatedQuizId" TEXT,
    "readyHref" TEXT,
    "errorCode" TEXT,
    "errorMessage" TEXT,
    "approvedAt" DATETIME,
    "startedAt" DATETIME,
    "completedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "CoachAction_studyPlanId_fkey" FOREIGN KEY ("studyPlanId") REFERENCES "StudyPlan" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CoachLesson" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "studyPlanId" TEXT NOT NULL,
    "actionId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "conceptKey" TEXT NOT NULL,
    "sections" TEXT NOT NULL,
    "misconception" TEXT NOT NULL,
    "workedExample" TEXT,
    "summary" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" DATETIME,
    CONSTRAINT "CoachLesson_studyPlanId_fkey" FOREIGN KEY ("studyPlanId") REFERENCES "StudyPlan" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CoachLesson_actionId_fkey" FOREIGN KEY ("actionId") REFERENCES "CoachAction" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CoachLessonEvidence" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "lessonId" TEXT NOT NULL,
    "sourceChunkId" TEXT NOT NULL,
    "quote" TEXT NOT NULL,
    "displayOrder" INTEGER NOT NULL,
    CONSTRAINT "CoachLessonEvidence_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "CoachLesson" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CoachLessonEvidence_sourceChunkId_fkey" FOREIGN KEY ("sourceChunkId") REFERENCES "SourceChunk" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CoachRun" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "studyPlanId" TEXT NOT NULL,
    "trigger" TEXT NOT NULL,
    "candidateActions" TEXT NOT NULL,
    "selectedActionType" TEXT,
    "selectedActionId" TEXT,
    "provider" TEXT,
    "model" TEXT,
    "durationMs" INTEGER NOT NULL,
    "inputTokens" INTEGER,
    "outputTokens" INTEGER,
    "status" TEXT NOT NULL,
    "policyRejected" BOOLEAN NOT NULL DEFAULT false,
    "errorCode" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CoachRun_studyPlanId_fkey" FOREIGN KEY ("studyPlanId") REFERENCES "StudyPlan" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "Session_sessionToken_key" ON "Session"("sessionToken")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "VerificationToken_token_key" ON "VerificationToken"("token")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "ConceptReview_userId_sourceQuizId_conceptKey_key" ON "ConceptReview"("userId", "sourceQuizId", "conceptKey")`,
  `CREATE INDEX IF NOT EXISTS "ConceptReview_userId_dueAt_idx" ON "ConceptReview"("userId", "dueAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "SourceDocument_userId_contentHash_key" ON "SourceDocument"("userId", "contentHash")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "SourceChunk_sourceDocumentId_ordinal_key" ON "SourceChunk"("sourceDocumentId", "ordinal")`,
  `CREATE INDEX IF NOT EXISTS "SourceChunk_sourceDocumentId_idx" ON "SourceChunk"("sourceDocumentId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "SourceReference_sourceDocumentId_url_key" ON "SourceReference"("sourceDocumentId", "url")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "QuizBlueprintItem_quizId_slot_key" ON "QuizBlueprintItem"("quizId", "slot")`,
  `CREATE INDEX IF NOT EXISTS "QuizBlueprintItem_quizId_batchIndex_idx" ON "QuizBlueprintItem"("quizId", "batchIndex")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "QuizGenerationBatch_quizId_batchIndex_key" ON "QuizGenerationBatch"("quizId", "batchIndex")`,
  `CREATE INDEX IF NOT EXISTS "QuizGenerationBatch_quizId_status_idx" ON "QuizGenerationBatch"("quizId", "status")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "QuestionEvidence_questionId_displayOrder_key" ON "QuestionEvidence"("questionId", "displayOrder")`,
  `CREATE INDEX IF NOT EXISTS "GenerationTrace_quizId_stage_idx" ON "GenerationTrace"("quizId", "stage")`,
  `CREATE INDEX IF NOT EXISTS "GenerationTrace_stage_createdAt_idx" ON "GenerationTrace"("stage", "createdAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "StudyPlan_activeKey_key" ON "StudyPlan"("activeKey")`,
  `CREATE INDEX IF NOT EXISTS "StudyPlan_userId_status_idx" ON "StudyPlan"("userId", "status")`,
  `CREATE INDEX IF NOT EXISTS "StudyPlanSource_sourceDocumentId_idx" ON "StudyPlanSource"("sourceDocumentId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "PlanConcept_studyPlanId_conceptKey_key" ON "PlanConcept"("studyPlanId", "conceptKey")`,
  `CREATE INDEX IF NOT EXISTS "PlanConcept_studyPlanId_sourceDocumentId_idx" ON "PlanConcept"("studyPlanId", "sourceDocumentId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CoachThread_studyPlanId_key" ON "CoachThread"("studyPlanId")`,
  `CREATE INDEX IF NOT EXISTS "CoachMessage_threadId_createdAt_idx" ON "CoachMessage"("threadId", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "CoachAction_studyPlanId_status_createdAt_idx" ON "CoachAction"("studyPlanId", "status", "createdAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CoachLesson_actionId_key" ON "CoachLesson"("actionId")`,
  `CREATE INDEX IF NOT EXISTS "CoachLesson_studyPlanId_createdAt_idx" ON "CoachLesson"("studyPlanId", "createdAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CoachLessonEvidence_lessonId_displayOrder_key" ON "CoachLessonEvidence"("lessonId", "displayOrder")`,
  `CREATE INDEX IF NOT EXISTS "CoachRun_studyPlanId_createdAt_idx" ON "CoachRun"("studyPlanId", "createdAt")`,
];

// Columns added after the initial tables shipped. SQLite has no
// "ADD COLUMN IF NOT EXISTS", so these run individually and the "duplicate
// column name" error is swallowed (see ensureSchema in lib/db.ts). This lets an
// already-provisioned DB (e.g. a live Turso instance) self-upgrade on first use.
export const ADDITIVE_COLUMNS: string[] = [
  `ALTER TABLE "Quiz" ADD COLUMN "groundingText" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "verificationStatus" TEXT NOT NULL DEFAULT 'pending'`,
  `ALTER TABLE "Quiz" ADD COLUMN "verifiedAt" DATETIME`,
  `ALTER TABLE "Quiz" ADD COLUMN "verifierModel" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "verificationSummary" TEXT`,
  `ALTER TABLE "Question" ADD COLUMN "verdict" TEXT`,
  `ALTER TABLE "Question" ADD COLUMN "verificationDetail" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "generatorModel" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "generatorPromptHash" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "verifierPromptHash" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "purpose" TEXT NOT NULL DEFAULT 'standard'`,
  `ALTER TABLE "Quiz" ADD COLUMN "sourceQuizId" TEXT`,
  `ALTER TABLE "Question" ADD COLUMN "reviewConceptKey" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "sourceDocumentId" TEXT`,
  `ALTER TABLE "Quiz" ADD COLUMN "generationStatus" TEXT NOT NULL DEFAULT 'legacy'`,
  `ALTER TABLE "Quiz" ADD COLUMN "targetQuestionCount" INTEGER`,
  `ALTER TABLE "Quiz" ADD COLUMN "firstBatchReadyAt" DATETIME`,
  `ALTER TABLE "Quiz" ADD COLUMN "generationError" TEXT`,
  `ALTER TABLE "Question" ADD COLUMN "blueprintItemId" TEXT`,
  `ALTER TABLE "Question" ADD COLUMN "optionExplanations" TEXT`,
  `ALTER TABLE "Question" ADD COLUMN "evidenceStatus" TEXT NOT NULL DEFAULT 'missing'`,
  `ALTER TABLE "QuizBlueprintItem" ADD COLUMN "failureCode" TEXT`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "Question_blueprintItemId_key" ON "Question"("blueprintItemId")`,
];
